name: Python package
on: 
  push:
   branches: new-feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to new feature branch
        uses: actions/checkout@v4
        with:
          ref: new-feature
      - name: branch check 
        run: git branch
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies

        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

      - name: Test on new-feature branch
        if: github.ref == 'refs/heads/new-feature'
        run: |
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        continue-on-error: true
      - name: checkout to main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Merge changes to main branch
        run: |
          git branch
          git merge --no-ff origin/new-feature
    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Deploy on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t shashidas/python-fast-app:py -f Dockerfile .
          docker push shashidas/python-fast-app:py
